default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: localhost

production:
  <<: *default
  database: db/production.sqlite3


development:
  <<: *default
  database: database-1

test:
  <<: *default
  database: database-1

production:
  <<: *default
  database: database-1
  username: root
  password: password  